# Generated by Django 6.0.2 on 2026-03-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_buyer_uniquecart_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('sub_total', models.PositiveIntegerField(default=0)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.uniquecart')),
            ],
        ),
    ]
